### ISSUE TITLE
Initial Value of Grid With

### ISSUE THREAD

**Issue by rumbleFTW** [Souvik2376/Pixel-Art#1]
In the initial drawing page, a page can be created with 0 Grid With and 0 Grid Height. But still, it shows a Grid with height 1 and width 1.

## Suggested changes:
In index.html, 
```html
<span id="height-value">01</span>
```
```html
<span id="width-value">01</span>
```

**Comment by Souvik2376** [comment]
Ok . My bad , got it  👍 . Thanks man 💯
